### ISSUE TITLE
internal server error on change products

### ISSUE THREAD

**Issue by seebi** [OpenOlitor/openolitor-server#537]
Currently I get this error

```
Produkt konnte nicht gespeichert werden. Fehler: 500-Internal Server Error:[object Object]
```

Location: https://sunu2-test.applicationcloud.io/admin/#/produkte

**Comment by fabianpage** [comment]
Hi Sebastian
Can you please try again? Last night swisscom did an upgrade of their cloud infrastructure.
Thanks
Fabian

**Comment by seebi** [comment]
The error appeared imho when changing lots of products fastly one behind the other.

I tested this now again and was not able to re-produce this anymore.

so I close the issue
