### ISSUE TITLE
deployment with local storage and without docker

### ISSUE THREAD

**Issue by amo13** [OpenOlitor/openolitor-server#587]
Hello and thanks for publishing this project open source under a free license!

I'd like to setup and deploy an instance for friends launching a CSA (SoLaWi). The server I'd run it on already has a MariaDB running and it would be awesome if I could use that instead of spinning up a new one with docker, especially since it would be the only thing I'd need docker for and I'd like to avoid it.

Can you give me some hints on how to get openolitor running with local storage (no AWS buckets) and a local MariaDB (no docker)?

Any help would be greatly appreciated.

**Comment by toggm** [comment]
If you want to connect to an external database, just pre-create the correct database schema based on https://github.com/OpenOlitor/openolitor-server/blob/prod/docker/mariadb/scripts/sql/db_schema.sql and configure the correct JDBC urls in the `application.conf`

- https://github.com/OpenOlitor/openolitor-server/blob/prod/src/main/resources/application.conf#L271
- https://github.com/OpenOlitor/openolitor-server/blob/prod/src/main/resources/application.conf#L279

**Comment by amo13** [comment]
Awesome, thank you very much! Looks like it is starting just fine.

I have a few more small questions, I hope I do not bother you:
- Upon startup, the server is complaining about s misconfigured S3 bucket. This is because I don't use AWS. Is there something I need to do in order to use local storage instead or can I simply ignore the message? Under what path would files get stored if using local storage?
- What will I need to do when new versions are released? Simply overwrite everything with the new files but keep the modified lines of the configuration file(s)?
- Do I need to run database migrations manually somehow? (Like for a django or rails project for example)
- I am having trouble setting up the nodejs dependencies for the frontends. Where can I see which versions I need (nodejs, npm, grunt, bower, etc. - are you really using ancient node-gyp 3.8?). I get a lot of errors when trying to `npm install`, looks like node-sass refuses to compile. Using NVM might do the trick, but I am not sure which versions to select.

I'd be very grateful if you could drop some quick answers. Thank you for your help!

**Comment by toggm** [comment]
@amo13 

#### S3
Do you see the following error on startup:
```
Could not create buckets. com.amazonaws.services.s3.model.AmazonS3Exception: Your previous request to create the named bucket succeeded and you already own it
```
If yes, then you can ignore the error as it is raised on an upcoming restart once the buckets where created successfully. If not, please post the log message.

#### Configuration/Release management
We use Typesafe config to initialize the application. So to be able to customize your configuration, I suggest you keep your customized configuration externally and start the application referring to this configuration (https://github.com/lightbend/config/tree/v1.3.3#standard-behavior).
On a new release you should check for differences in the configuration and of course merge them to your customized configuration.

#### Database migrations
You don't have to run database migrations manually. OpenOlitor uses a database evolution and checks the current state of the database on startup

#### OpenOlitor dev dependencies
The OpenOlitor client still runs with angularjs and is not yet migrated to the latests node version. I can successfully run the application with the following versions:
- bower: 1.8.8
- nodejs: 12.21.0
- npm: 6.14.4
- grunt: 1.0.4
- grunt-cli: 1.3.2


Hope this helps.

**Comment by amo13** [comment]
Amazing! Thank you so much for your help! I was able to set it up and everything connects and is working.
I (sort of) documented all I had to do and would submit a pull request if you'd be willing to add it to your docs wiki.

---

Only a few things are left:
#### Storage

The S3 error I am seeing is not the same as yours but this one:
```
ERROR c.o.c.f.DefaultFileStoreComponent  - Error creating buckets for csa1: Could not create buckets. com.amazonaws.SdkClientException: Unable to execute HTTP request: Connect to localhost:9050 [localhost/127.0.0.1, localhost/0:0:0:0:0:0:0:1] failed: Connection refused (Connection refused)
```
This is certainly because I do not (wish to) configure S3. I'd actually like to use only local storage.
A similar error occurs when I try to upload a logo to the admin interface:
```
File of file type ProjektStammdaten with id logo could not be stored. Error: FileStoreError(Could not put file. com.amazonaws.SdkClientException: Unable to execute HTTP request: Connect to localhost:9050 [localhost/127.0.0.1, localhost/0:0:0:0:0:0:0:1] failed: Connection refused (Connection refused))
```
What do I need to do in order to avoid S3 altogether and set up a local folder for storage?

#### a few errors I noticed in my nginx logs
I found the following errors in my nginx logs when opening the main frontend (kundenportal). Maybe they are unimportant, but I thought I'd post them anyway. Looks like they are related to some font stuff.
```
/srv/openolitor/bower_components/bootstrap/dist/fonts/glyphicons-halflings-regular.woff2" failed (2: No such file or directory), client: 192.168.122.1, server: 192.168.122.234, request: "GET /bower_components/bootstrap/dist/fonts/glyphicons-halflings-regular.woff2 HTTP/1.1", host: "192.168.122.234", referrer: "http://192.168.122.234/styles/7050f3d5.vendor.css
/srv/openolitor/bower_components/bootstrap/dist/fonts/glyphicons-halflings-regular.woff2" failed (2: No such file or directory), client: 192.168.122.1, server: 192.168.122.234, request: "GET /bower_components/bootstrap/dist/fonts/glyphicons-halflings-regular.woff2 HTTP/1.1", host: "192.168.122.234", referrer: "http://192.168.122.234/styles/7050f3d5.vendor.css
/srv/openolitor/bower_components/bootstrap/dist/fonts/glyphicons-halflings-regular.woff" failed (2: No such file or directory), client: 192.168.122.1, server: 192.168.122.234, request: "GET /bower_components/bootstrap/dist/fonts/glyphicons-halflings-regular.woff HTTP/1.1", host: "192.168.122.234", referrer: "http://192.168.122.234/styles/7050f3d5.vendor.css
/srv/openolitor/bower_components/bootstrap/dist/fonts/glyphicons-halflings-regular.ttf" failed (2: No such file or directory), client: 192.168.122.1, server: 192.168.122.234, request: "GET /bower_components/bootstrap/dist/fonts/glyphicons-halflings-regular.ttf HTTP/1.1", host: "192.168.122.234", referrer: "http://192.168.122.234/styles/7050f3d5.vendor.css
```
and, maybe related, this shows up when doing a `grunt build` for the kundenportal:
```
Running "cssmin:generated" (cssmin) task
>> Skipping remote @import of "https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,700" as no callback given.
```
Another error I noticed in the nginx log (and in the firefox console) on the kundenportal page is:
```
/srv/openolitor/{{API_URL}}open/projekt/1/logo" failed (2: No such file or directory), client: 192.168.122.1, server: 192.168.122.234, request: "GET /%7B%7BAPI_URL%7D%7Dopen/projekt/1/logo HTTP/1.1", host: "192.168.122.234", referrer: "http://192.168.122.234/
```
Is it possible that somehow `{{API_URL}}` in the `index.html` file is not replaced with the URL set in `app/environments/config.js`?

#### switching from development to production
What do I need to do to declare the environment to be a production instead of a development environment? Chanching "dev" to "production" in the two config.js frontend files did not do the trick.

**Comment by amo13** [comment]
In the meantime, I managed to set ENV to `prod` instead of `dev` and my deployment now *looks* like a productive deployment. Still, the information popup in the bottom right corner of the web UI displays `#dev` flags for the frontend and the backend:
![Screenshot from 2021-06-24 10-17-26](https://user-images.githubusercontent.com/6617661/123228617-dd3fca80-d4d5-11eb-9a30-7037893b5dc0.png)
How can I set the frontend and backend to production mode? Or is it nothing but a flag without importance whatsoever?

---

As for the replacement of S3 with local storage, I have absolutely no idea how to go about this. I tried to understand the configuration and code setting up S3 so I could modify it to use local storage, but I did not get very far...
Any help with this would be greatly appreciated.

**Comment by toggm** [comment]
As for your question regarding S3:
OpenOlitor is designed to run in a cloud environment, therefore there is not support for local storage only. What you could do is run a local s3 server (i.e. https://medium.com/the-innovation/running-s3-object-storage-locally-with-minio-f50540ffc239).

**Comment by mcmpp** [comment]
Hi @amo13 , 

the API_URL is a variable that we define and assign dynamically on the config.js. See it here: https://github.com/OpenOlitor/openolitor-docker-compose/blob/master/config/client/admin/config.js
This function is injected when the client container is started and helps each instance to redirect the calls to the right endpoint to the server.  

When you run it without docker, there is a default configuration in here: https://github.com/OpenOlitor/openolitor-client-kundenportal/blob/prod/app/environments/config.js
It seems in your setup these variables are not initialized as we can see that the {{API_URL}} was not replace with the right value. I am not sure why and I would need more context to see what is happening. Is there any log entry where this config.js is mentioned??

As you are running only one instance, another way to proceed is to replace all variables with the static value statically. This would imply changes in the code. This changes would make more complicated the maintenance of your instance as the version would differ from the prod version. Could you explain us what is your plan in order to keep the instance updated ??

Once we have this solved, we can move to the font issue. 

Have a great day

**Comment by amo13** [comment]
Thank you a lot for your continued help with this, both @toggm and @mcmpp !

The hint to minio was awesome, and - shame on me - I guess I could have found it in the repo... Didn't know until now what minio is and what it is good for. Now I understand :) Anyway, the local file storage with S3 is solved!

#### {{API_URL}}
As for the `{{API_URL}}` not being replaced, unfortunately, I can't find any more logs concerning this than the nginx log. Of course, it is also visible on the web console in my firefox when I open the kundenportal login page. The web console says:
```
GEThttp://192.168.122.234/%7B%7BAPI_URL%7D%7Dopen/projekt/1/logo
[HTTP/1.1 404 Not Found 2ms]
```
Interestingly enough, the logo I uploaded with the admin interface before is shown correctly on the top left. 

To my understanding, the process which should replace the variable with the content from the configuration file should probably be the `grunt build` call. But I don't see anything suspicious [there](https://paste.c-net.org/ChiefDuarte).

The [logs on the server side](https://paste.c-net.org/CadillacMisled) also seem okay to me, no error messages there either. I start the server by running `sbt run -Dconfig.file=/etc/openolitor.conf`.

#### Updating
My plan for keeping everything up to date is to download new releases from github and
* overwrite the server part with the new release then restart the server (the config file is located somewhere else so it is safe; check for changes that would need merging)
* unpack both frontends, adjust both respective `app/environments/config.js` contents and `grunt build` them
* move the resulting `dist` folders to the directory served by nginx (subdir `admin` for the admin frontend)

#### SMTP
In the current state, it looks like it is generally working. The only thing left that got me confused is how to test sending email. I put my smtp info and credentials in the server configuration file but I am not sure how to test it.
I tried adding a participant, creating a subscription for that user and manually creating an invoice. If I click onto that invoice and then open the drop-down menu in the top right corner, I can click on "invoice sent", but nothing happens then. The [server logs](https://paste.c-net.org/ColoniesFerguson) also don't seem to show any error while doing that.
My smtp config part in `/etc/openolitor.conf` looks like this:
```
openolitor {
  run-proxy-service: true,
  port: 9003,
  mandanten: ["csa1"],
  csa1: {
...
    smtp {
      from = "a***@***.org"
      endpoint = "***.org"
      port = 587
      user = "a***@***.org"
      password = "***"
      security="STARTTLS"
      number-of-retries = 5
      send-email = true
      max-chunk-size = 1m
      bcc = "b***@***.org"
    }
...
}
```

**Comment by mcmpp** [comment]
Hi @amo13 ,

I am glad that most of the features are working. Please, let us know about your experience with it and do not hesitate to participate on the different steps of making this software available for all groups that would benefit from using it. I would also like to advise you to keep in touch with the sunu association (info@sunu.eu) that regroups all OpenOlitor users in Germany. I am also making part of this association and our aim is to facilitate the digital tools for the CSA groups and helping all groups to keep in touch.

Here a couple of answers: 

* you are right with the issue of the API_URL. We also have this error even though we didn't realize because the logo is correctly transferred. I am going to create a ticket to investigate and solve this issue. 
* You can register yourself and invite yourself to the customer portal. This should send you an email with a link in it. Here a demo: 

![inviting](https://user-images.githubusercontent.com/13901369/125622363-320c5c67-676a-4210-ae6a-f18072faeb0d.gif)

as a result of this "send invite" an email should have being send to your email

**Comment by amo13** [comment]
Wow, thank you so much for your help with setting it up on "bare metal"!
I can now confirm that sending emails does work fine for me too.

One last thing is left for me to ask about: 

![](https://user-images.githubusercontent.com/6617661/123228617-dd3fca80-d4d5-11eb-9a30-7037893b5dc0.png)

Does the mention of `#dev` has any functional meaning or implication or is it only something cosmetic? Does the UI and WS behave differently if I set them to production mode? And if so, how would I do that?

**Comment by mcmpp** [comment]
Hi @amo13 ,

I am glad that this is working!! 
The environment label is only an indicator. You can change it in this file.  https://github.com/OpenOlitor/openolitor-client-admin/blob/prod/app/environments/config.js

Please, keep us informed about your experience!

**Comment by amo13** [comment]
Hey @mcmpp, thank you for your reply. 

I did change ENV in this exact file. The change only affects the third indicator (ENV) though, as shown in the screenshot. What about the indicators for UI and WS? 

Thank you so much for your continued support! Closing this since everything is running now =)
